### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by keplerg** [CCurl/s3#1]
When defining a function if you leave the terminating semicolon off the end of the definition the code throws a segmentation fault. For example:

:Test 1 2 3

This can be fixed by changing fCreate to check for the null byte making the semicolon optional:

/*  :  */ void fCreate() { p=funcN(p); if (fa) { printf("-redef:%ld at %ld-", fn, fa); }
    while (stb[p]==' ') { ++p; } funcs[fn]=p;
    while (stb[p++]!=';' && stb[p]!='\0') {}
    if (h<p) { h=p; } st.i[0]=h; }

**Comment by keplerg** [comment]
To support multiple line word definitions you could use the following (note your code is a bit cryptic so I am not sure I got all the edge cases):

void fCreate() {
    p=funcN(p); if (fa) { printf("-redef:%ld at %ld-", fn, fa); }
    while (stb[p]==' ') { ++p; } funcs[fn]=p;
    while (stb[p++]!=';') {
        if (stb[p]=='\n') {
            if (fp == (long)stdin) { printf(": "); }
            fgets(&stb[p], 128, (FILE*)fp);
        }
    }
    if (h<p) { h=p; } st.i[0]=h;
}

**Comment by CCurl** [comment]
Wow, this is great .. thanks! I just saw your PR. Unfortunately, I have also made some tweaks in those areas, so there are merge conflicts. It looks like your work was done in a Fork, so I think you would have to resolve the conflicts in order to complete the PR. Or I can incorporate your suggestions into the main branch and you can abandon your PR. But I'd like the history to show that you made this contribution.

**Comment by CCurl** [comment]
OK, so I have incorporated your changes into the main branch. This is awesome, thanks!

**Comment by keplerg** [comment]
Thanks, I was wondering if you saw my fork or not. By the way I am thinking of adding an interactive option using ncurses so you can bring up (and edit) history. This would be a compile option so you can go back to the original when you have done your debugging. I'll let you know how I make out.

**Comment by CCurl** [comment]
I didn't see it until tonight, sorry. On Windows, you get that automatically. On Linux, that would be a nice feature to add. Maybe add it as a separate file (*.inc maybe) and then just 1 line in s3.cpp that we can comment out when we don't need it.
