### ISSUE TITLE
string to integer

### ISSUE THREAD

**Issue by arblake** [CCurl/s3#12]
Hi, this is more of a request. How would you convert an integer string into an integer ... efficiently?
From a string I can extract a sub string containing only numbers but now need to efficiently convert that into an integer for further manipulation.
I read that q4 is faster but it lacks features, and c4 has many features, but speed or efficiency how does it compare?

**Comment by CCurl** [comment]
Here is how I would take a string of numbers and turn it into a number in s3:

0( BTWI: n l h -- f ... Between-Inclusive )
:BTWI l+ s3 s2 s1 r1 r2 <~ r1 r3 >~ b& l-;

0( STOI: a--n ... StringToInteger )
:STOI l+ s1 0 {10* r1 c@ '0- + i1 r1 c@ '0'9 BTWI} l-;

NB: this assumes you already know it's a string of digits.

Of course, if you want, you can remove all the spaces to improve performance, at the expense of making it harder to read.

**Comment by CCurl** [comment]
As to performance, the VM that c4 compiles to is very similar to s3. Since this code is essentially what c4 would compile to (without the spaces of course, and the call to BTWI is direct, not hashed at runtime), so c4 is maybe a little more efficient, but not much. But c4 is more readable.

**Comment by CCurl** [comment]
So I just added a way to execute a dynamically built string, using xE. For example:
2000#|"hi there!"74665|\
2000 xE
This will print 'hi there!' and push 74665 onto the stack.
The only thing would be: don't create a function using xE.
![image](https://user-images.githubusercontent.com/14334380/215302204-f8a3ec91-d07c-4481-aed9-9657fc8f6a97.png)

**Comment by arblake** [comment]
Thanks --- STOI works well.
