### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by arblake** [CCurl/s3#13]
Hi,
Latest version has a compile error:
.
.
.
/usr/bin/ld: /tmp/s3-6add44.o: in function `fExt()':
s3.cpp:(.text+0x2782): undefined reference to `Run(int, int)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ls: cannot access './s3': No such file or directory
adrian@adrian-hp:~/s3$ ^C

**Comment by CCurl** [comment]
Sorry, I'm not good at seeing these posts quickly. I wasn't getting this on Windows builds. I changed the signature of the forward-reference to match the implementation.

**Comment by arblake** [comment]
Thanks, fixed
